import{a as L,i as c,S as f}from"./assets/vendor-b11e2a50.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();async function h(s,e=1,o=15){const n="https://pixabay.com/api/",t=new URLSearchParams({key:"45077635-6eb8c9a3980485254b901d63b",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:o});try{return(await L.get(`${n}?${t}`)).data}catch(r){iziToast.error({title:"Error",message:r.message,position:"center"})}}function p(s){const e=document.querySelector(".gallery"),o=s.map(n=>`<li>
                <a href="${n.largeImageURL}">
                  <img src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
                </a>
                <ul class="info">
                  <li><span>Likes:</span> ${n.likes}</li>
                  <li><span>Views:</span> ${n.views}</li>
                  <li><span>Comments:</span> ${n.comments}</li>
                  <li><span>Downloads:</span> ${n.downloads}</li>
                </ul>
              </li>`).join("");e.insertAdjacentHTML("beforeend",o)}const b=document.querySelector("#search-form"),y=document.querySelector(".gallery"),u=document.querySelector("#loader-top"),m=document.querySelector("#loader-bottom"),a=document.querySelector(".js-load-more-btn");let l,i=1,g="";b.addEventListener("submit",w);a.addEventListener("click",S);async function w(s){s.preventDefault();const e=s.target.elements.query.value.trim();if(e===""){c.info({message:"Search query cannot be empty!",position:"center"});return}y.innerHTML="",u.classList.remove("hidden"),a.classList.add("hidden"),i=1;try{const o=await h(e,i);if(u.classList.add("hidden"),o.hits.length===0){c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"center"});return}p(o.hits),l=new f(".gallery a"),l.refresh(),a.classList.remove("hidden"),i+=1,g=e}catch(o){u.classList.add("hidden"),c.error({title:"Error",message:o.message,position:"center"})}}async function S(s){s.preventDefault(),m.classList.remove("hidden"),a.classList.add("hidden");try{const e=await h(g,i);p(e.hits),l=new f(".gallery a"),l.refresh(),i+=1,i*15>=e.totalHits?(a.classList.add("hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):a.classList.remove("hidden"),m.classList.add("hidden"),v()}catch(e){m.classList.add("hidden"),c.error({title:"Error",message:e.message,position:"center"})}}function v(){const s=y.firstElementChild;if(!s)return;const o=s.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
