import{a as g,i as l,S as h}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const u of t.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function p(o,r=1,n=15){const s="https://pixabay.com/api/",e=new URLSearchParams({key:"45077635-6eb8c9a3980485254b901d63b",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n});try{return(await g.get(`${s}?${e}`)).data}catch(t){iziToast.error({title:"Error",message:t.message,position:"center"})}}function y(o){const r=document.querySelector(".gallery"),n=o.map(s=>`<li>
                <a href="${s.largeImageURL}">
                  <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
                </a>
                <ul class="info">
                  <li><span>Likes:</span> ${s.likes}</li>
                  <li><span>Views:</span> ${s.views}</li>
                  <li><span>Comments:</span> ${s.comments}</li>
                  <li><span>Downloads:</span> ${s.downloads}</li>
                </ul>
              </li>`).join("");r.insertAdjacentHTML("beforeend",n)}const L=document.querySelector("#search-form"),b=document.querySelector(".gallery"),m=document.querySelector("#loader-top"),c=document.querySelector("#loader-bottom"),a=document.querySelector(".js-load-more-btn");let d,i=1,f="";L.addEventListener("submit",S);a.addEventListener("click",w);async function S(o){o.preventDefault();const r=o.target.elements.query.value.trim();if(r===""){l.error({title:"Error",message:"Search query cannot be empty!",position:"center"});return}b.innerHTML="",m.classList.remove("hidden"),i=1;try{const n=await p(r,i);if(m.classList.add("hidden"),c.classList.add("hidden"),n.hits.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}),a.classList.add("hidden");return}y(n.hits),d=new h(".gallery a"),d.refresh(),a.classList.remove("hidden"),i+=1,f=r}catch(n){m.classList.add("hidden"),l.error({title:"Error",message:n.message,position:"center"})}}async function w(o){o.preventDefault(),c.classList.remove("hidden"),a.classList.add("hidden");try{const r=await p(f,i);y(r.hits),d=new h(".gallery a"),d.refresh(),i+=1,i*15>=r.totalHits?(a.classList.add("hidden"),l.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"center"})):a.classList.remove("hidden"),c.classList.add("hidden"),q()}catch(r){c.classList.add("hidden"),l.error({title:"Error",message:r.message,position:"center"})}}function q(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
